#! /bin/sh
# Do common operations after a particular test.

if test -z "$debug"; then
  cd ..
  exec 1> /dev/null
  exec 2> /dev/null

  echo $echo_n "$out$echo_c" | cmp -s - $tmpdir/stdout || exit 1
  echo $echo_n "$err$echo_c" | cmp -s - $tmpdir/stderr || exit 1

  rm -rf $tmpdir
fi
