#! /bin/sh
# Do common operations before a particular test.

out=
err=

if test -z "$debug"; then
  mkdir $tmpdir
  cd $tmpdir

  case $top_srcdir in
    /*|~*) ;;
    *) top_srcdir=../$top_srcdir ;;
  esac

  case $srcdir in
    /*|~*) ;;
    *) srcdir=../$srcdir ;;
  esac

  echo $0 > checking
  exec 1> stdout
  exec 2> stderr

  PATH=..:../../src:$PATH
else
  set -x
  PATH=.:../src:$PATH
fi
