#! /bin/sh

# Test cpio by running regress.sh and checking output.  Splitting
# regress.sh into pieces is kind of a pain, to put it mildly.  So we
# do it this way instead.

# Never run this, since regress.sh isn't set up to handle it yet.
# Bummer!  I think the only problem is that error messages from tar
# are not correctly ignored when using fifos.  Maybe not a problem?
TESTINGFIFOS=

# Get all definitions.  Note that this changes our working directory
# to `testSubDir'.
here=`cd $srcdir && pwd`
. defs || exit 1
. $here/regress.sh

if test "$failed" -eq 0; then
   echo "========================"
   echo "All $count tests passed"
   echo "========================"
else
   echo "$failed of $count tests failed"
   exit 1
fi

exit 0
