#!/bin/sh
# Setup helper for `cpio' tests.

. ./atconfig

mkdir structure
cd structure
  echo foz > foo
  wrsparse
  mkdir tmp tmp2 tmp3 dev
  echo baz > bar

  if test "$FIFOS" = yes; then
    $MKFIFO pipe
    ln pipe copy
    $MKFIFO diff
    $MKFIFO dev/pipe2
    cat << EOF > missing1
structure/dev/pipe2
structure/pipe
structure/copy
structure/diff
EOF
    cat << EOF > missing2
structure/dev/pipe2: missing file.
structure/copy: missing file.
structure/diff: missing file.
structure/pipe: missing file.
EOF
  else
    : > missing1
    : > missing2
  fi

  cd tmp
    echo hello1 > hello
    test $SYMLINKS = yes && ln -s hello hello2
    ln hello hello3
    echo > world 'the world'
  cd ..
  cd tmp2
    test $SYMLINKS = yes && ln -s ../foo foolink
  cd ..
  cd tmp3
    mkdir tmp4
  cd ..
cd ..
